// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQf0pfapLtw8ff9I38mGobA77Dzwf3dY',
    appId: '1:603507359681:ios:cfae871f494d751c90b940',
    messagingSenderId: '603507359681',
    projectId: 'touchapp-65d7b',
    storageBucket: 'touchapp-65d7b.firebasestorage.app',
    iosBundleId: 'com.son.touch',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMdB7yam9cln1pGA4tu5vu1YSWQNYj0G4',
    appId: '1:603507359681:web:7895f46a455a7f6d90b940',
    messagingSenderId: '603507359681',
    projectId: 'touchapp-65d7b',
    authDomain: 'touchapp-65d7b.firebaseapp.com',
    storageBucket: 'touchapp-65d7b.firebasestorage.app',
    measurementId: 'G-V9134MRH68',
  );
}
